apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-management
  namespace: icb
  labels:
    app: gateway-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-management
  template:
    metadata:
      labels:
        app: gateway-management
    spec:
      containers:
      - name: gateway-management
        image: 10.10.10.3:5000/web/gateway-management:3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /publish/appsettings.json
          name: web-config
          subPath: gateway-management.json
        env:
          - name: ACB_MODE
            value: Test

      volumes:
      - name: web-config
        configMap:
          name: web-config
          items: 
          - key: gateway-management.json
            path: gateway-management.json
        
