kind: Service
apiVersion: v1
metadata:
  labels:
    app: gateway-management
  name: gateway-management
  namespace: icb
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30030
  selector:
    app: gateway-management

