kind: Service
apiVersion: v1
metadata:
  labels:
    app: gateway-app
  name: gateway-app
  namespace: icb
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
  selector:
    app: gateway-app

